
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=Michali

###

GET http://localhost:3000/posts/673f93a854f16b4155f3c18d

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello Shir",
    "owner": "Michali",
    "content": "Shir is the best"
}

###

PUT http://localhost:3000/posts/6740a2e5c8eb7cf50c7d9d99
Content-Type: application/json

{
    "title": "update title1",
    "owner": "moshe",
    "content": "update content"
}

###

POST http://localhost:3000/comments
Content-Type: application/json

{

    "postId": "677d767e1815bd58518421b6",
    "owner": "Mich",
    "content": "1111"
}

###

GET http://localhost:3000/comments

###

PUT http://localhost:3000/comments/6741f1bc669e2136817b3ca9
Content-Type: application/json

{
    "postId": "6741e9f8cfc2902388b0da1b",
    "owner": "Michali2",
    "content": "new commentsssssssssss"
}

###

GET http://localhost:3000/comments/677d76c31815bd58518421b8

###
DELETE http://localhost:3000/comments/6741f251203a3daab6a3e353

###

GET http://localhost:3000/comments?postId=677d767e1815bd58518421b6

###

GET http://localhost:3000/comments?owner=Mich&postId=677d767e1123815bd58518421b6

