
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=Michali

###

GET http://localhost:3000/posts/673f93a854f16b4155f3c18d

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello Shir2",
    "sender": "Michali2",
    "content": "Shir is the best2"
}

###

PUT http://localhost:3000/posts/6740a2e5c8eb7cf50c7d9d99
Content-Type: application/json

{
    "title": "update title1",
    "sender": "moshe",
    "content": "update content"
}