
###########################################################
##posts route
###########################################################

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=Michali

###

GET http://localhost:3000/posts/673f93a854f16b4155f3c18d

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "sdsdirs",
    "sender": "Michali",
    "content": "Shir is the best"
}

###

PUT http://localhost:3000/posts/6740a2e5c8eb7cf50c7d9d99
Content-Type: application/json

{
    "title": "update title1",
    "sender": "moshe",
    "content": "update content"
}

### delete post and all its comments

DELETE http://localhost:3000/posts/677e75a2633fe9fc8a32f05b

###########################################################
##Comments route
###########################################################

POST http://localhost:3000/comments
Content-Type: application/json

{

    "postId": "677e75a2633fe9fc8a32f05b",
    "sender": "michali",
    "content": "4"
}

###

GET http://localhost:3000/comments

###

PUT http://localhost:3000/comments/677d76c31815bd58518421b8
Content-Type: application/json

{
    "postId": "677d767e1815bd58518421b6",
    "sender": "Michali2",
    "content": "new commentsssssssssss"
}

###

GET http://localhost:3000/comments/677d76c31815bd58518421b8

###
DELETE http://localhost:3000/comments/677d76c31815bd58518421b8

### get all comments related to post id

GET http://localhost:3000/comments?postId=677e7367323dd4d7b4fc3791

###

GET http://localhost:3000/comments?sender=Mich&postId=677d767e1123815bd58518421b6

